# Generated by Django 4.2.16 on 2025-03-10 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todo_description_todo_due_date_todo_priority_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_all_todos", "Can view all todos")],
            },
        ),
    ]
