# Generated by Django 4.2.16 on 2025-03-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[("EMAIL", "Email"), ("NOTIF", "Notification")],
                        max_length=5,
                    ),
                ),
                (
                    "notification_time_value",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "notification_time_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MIN", "Minutes"),
                            ("HRS", "Hours"),
                            ("DAYS", "Days"),
                            ("WKS", "Weeks"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Track if notification is sent.",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("notification_time_unit", "MIN"),
                        ("notification_time_value__gte", 0),
                        ("notification_time_value__lte", 59),
                    ),
                    models.Q(
                        ("notification_time_unit", "HRS"),
                        ("notification_time_value__gte", 0),
                        ("notification_time_value__lte", 24),
                    ),
                    models.Q(
                        ("notification_time_unit", "DAYS"),
                        ("notification_time_value__gte", 0),
                        ("notification_time_value__lte", 28),
                    ),
                    models.Q(
                        ("notification_time_unit", "WKS"),
                        ("notification_time_value__gte", 0),
                        ("notification_time_value__lte", 4),
                    ),
                    models.Q(
                        ("notification_time_unit__exact", ""),
                        ("notification_time_value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="valid_notification_time_range",
            ),
        ),
    ]
