# Generated by Django 4.2.16 on 2025-03-09 08:58


from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    admin_group, _ = Group.objects.get_or_create(name="Admin")
    member_group, _ = Group.objects.get_or_create(name="Member")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_groups)]
