# Generated by Django 4.2.16 on 2025-03-11 18:17

import django.contrib.auth.models
from django.db import migrations
import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_groups"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
                ("assign", users.managers.CustomUserManager()),
            ],
        ),
    ]
